version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    environment:
      - SECRET_KEY=PROD!mrz-!q(@k^szgs2lp^3g9!8vi!8egp_uhgy%fff5aaa#x
      - DEBUG=true
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:3000 http://127.0.0.1:3000 http://86.58.81.87
      - CSRF_TRUSTED_ORIGINS=http://86.58.81.87
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=hello_django
      - DATABASE_USER=hello_django
      - DATABASE_PASSWORD=hello_django
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: