# Generated by Django 4.2 on 2023-05-04 10:09

from django.db import migrations, models

import stream.models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamprofile",
            name="stream_key",
            field=models.CharField(default=stream.models.generate_stream_key, max_length=32),
        ),
    ]
